name: "Judah"
description: "A digital ronin who writes occasionally"
meta_description: ""

aboutPage: false

gems:
  - jekyll-seo-tag
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

baseurl: /
domain_name: 'https:///kyoto-shift.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'syskit'

url:                'https:///kyoto-shift.github.io'
email:              'k@0px.moe'
author:             '0px'
authorTwitter:      'judahcaruso'
authorGithub:       'kyoto-shift'
authorFullName:     'Judah Caruso'
authorRealName:     'Judah'
authorHexName:      '0x6a75646168'
blogName:           "0x6a75646168"
twitter:
  username: judahcaruso

permalink:       /posts/:title/
defaults:
  -
    scope:
      path: "" # empty string for all files
      type: pages
    values:
      layout: default
  -
    scope:
      path: "" # empty string for all files
      type: posts
    values:
      layout: post
      use_toc: false
  -
    scope:
      path: ""
      type: drafts
    values:
      layout: post
  -
    scope:
      path: "_pages"
      type: pages
    values:
      permalink: /pages/:title/
      layout: post

collections:
  pages:
    output: true

plugins:
    - jekyll-pants
